/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseField: typeof import('./src/components/BaseField/index.vue')['default']
    NutActionSheet: typeof import('nutui-uniapp/components/actionsheet/actionsheet.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutCellGroup: typeof import('nutui-uniapp/components/cellgroup/cellgroup.vue')['default']
    NutCheckbox: typeof import('nutui-uniapp/components/checkbox/checkbox.vue')['default']
    NutCollapse: typeof import('nutui-uniapp/components/collapse/collapse.vue')['default']
    NutCollapseItem: typeof import('nutui-uniapp/components/collapseitem/collapseitem.vue')['default']
    NutDatePicker: typeof import('nutui-uniapp/components/datepicker/datepicker.vue')['default']
    NutEmpty: typeof import('nutui-uniapp/components/empty/empty.vue')['default']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['default']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutInputNumber: typeof import('nutui-uniapp/components/inputnumber/inputnumber.vue')['default']
    NutMenu: typeof import('nutui-uniapp/components/menu/menu.vue')['default']
    NutMenuItem: typeof import('nutui-uniapp/components/menuitem/menuitem.vue')['default']
    NutPicker: typeof import('nutui-uniapp/components/picker/picker.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutTabbar: typeof import('nutui-uniapp/components/tabbar/tabbar.vue')['default']
    NutTabbarItem: typeof import('nutui-uniapp/components/tabbaritem/tabbaritem.vue')['default']
    TabBar: typeof import('./src/components/TabBar/index.vue')['default']
  }
}
