/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseField: typeof import('./src/components/BaseField/index.vue')['default']
    NutAvatar: typeof import('nutui-uniapp/components/avatar/avatar.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutCellGroup: typeof import('nutui-uniapp/components/cellgroup/cellgroup.vue')['default']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['default']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutPicker: typeof import('nutui-uniapp/components/picker/picker.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutSearchbar: typeof import('nutui-uniapp/components/searchbar/searchbar.vue')['default']
    NutTabbar: typeof import('nutui-uniapp/components/tabbar/tabbar.vue')['default']
    NutTabbarItem: typeof import('nutui-uniapp/components/tabbaritem/tabbaritem.vue')['default']
    NutTextarea: typeof import('nutui-uniapp/components/textarea/textarea.vue')['default']
    TabBar: typeof import('./src/components/TabBar/index.vue')['default']
    TeamCard: typeof import('./src/components/TeamCard/index.vue')['default']
  }
}
